env:
  matrix:
    - MAGE_PHP='5.5-1.7' PHP_VERSION='5.5' MAGE_VERSION='1.7.0.2-patch10'
    - MAGE_PHP='5.5-1.8' PHP_VERSION='5.5' MAGE_VERSION='1.8.1.0-patch4'
    - MAGE_PHP='5.5-1.9' PHP_VERSION='5.5' MAGE_VERSION='1.9.2.4'
    - MAGE_PHP='5.6_1.8' PHP_VERSION='5.6' MAGE_VERSION='1.8.1.0-patch4'
    - MAGE_PHP='5.6-1.9' PHP_VERSION='5.6' MAGE_VERSION='1.9.2.4'
build:
  pre_ci:
    - sed -i -e s/{PHP_VERSION}/$PHP_VERSION/g Dockerfile
    - docker build --rm=true --pull=true --force-rm=true --no-cache=true --tag=mygento/php:$MAGE_PHP .
  pre_ci_boot:
    image_name: mygento/hamster
    image_tag: $MAGE_PHP
    pull: false
  ci:
     - php -v
     - ls -la /opt/magento/
  post_ci:
    - docker push mygento/php:$PHP_TAG
integrations:
    hub:
      - integrationName: Docker
        type: docker
        #agent_only: true
