language: php

script: true

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0


env:
  matrix:
    - MAGENTO_VERSION=magento-mirror-1.9.2.2
    - MAGENTO_VERSION=magento-mirror-1.8.1.0
    - MAGENTO_VERSION=magento-mirror-1.7.0.2
